### ISSUE TITLE
Support creating books in their own folders

### ISSUE THREAD

**Issue by chancez** [myxdvz/booktree#3]
So far this is working pretty good, but it seems that books in a given series are being grouped until a single "book" due to the fact that the files are all in the same folder. For example: 

![Screenshot 2024-08-22 at 1 34 25 PM](https://github.com/user-attachments/assets/9e54b33a-feca-4d95-a061-a212cb37f477)

Ideally each of these books would be in their own directory, so they can be played separately. Right now all the chapters are combined making it hard to find where each book ends and starts.

**Comment by myxdvz** [comment]
This should be supported, the script assumes that each folder IS a book. In cases where the folder contains multiple books, pass the flag --multibook to treat each file as a potential book
