### ISSUE TITLE
REQUEST: Multi-author book targetPath

### ISSUE THREAD

**Issue by tigerkzr** [myxdvz/booktree#6]
Suggest the books that are a collection of stories from many authors receive a target path of the book name instead of first author.  

Example Book: [Legends Stories by the Masters of Fantasy, Volume 1,2 and 4](https://www.myanonamouse.net/t/489745)

would go in as follows:
```
/ABS/Legends Stories by the Masters of Fantasy/Legends Stories by the Masters of Fantasy - Volume 1
/ABS/Legends Stories by the Masters of Fantasy/Legends Stories by the Masters of Fantasy - Volume 2
/ABS/Legends Stories by the Masters of Fantasy/Legends Stories by the Masters of Fantasy - Volume 4

```
Currently fixing in log file

I realize this might take some if..then/regex trickery. Might not be worth the pursuit unless you get bored one day. :P

**Comment by myxdvz** [comment]
Multi-author support has been added - in the config file, add multi_author in the target paths section.  

first_author - uses the first author in the list
authors - creates a folder with all author names
Use an actual string if you want to identify a specific folder name like "Various" or "Anthologies"
Use an empty string "" if you do not want to have an author folder

        "target_path": {
            "multi_author": "first_author",
            "in_series": "{author}/{series}/{series} #{part} - {title}",
            "no_series": "{author}/{title}",
            "disc_folder": "{title} {disc}"
        },
