### ISSUE TITLE
Command line arguments not recognized

### ISSUE THREAD

**Issue by tigerkzr** [myxdvz/booktree#7]
Trying to run on log mode. This is with the GitHub repo version.  The docker version gives me the same responses. The directories in the below command are just the files the docker container uses. All dirs and file names are the same for docker vs GitHub versions.

`python3 booktree.py log --file /docker/booktree/logs/booktree_log.csv --dry-run /docker/booktree/config/config.json`

```
usage: booktree [-h] [-dc DEFAULT_CONFIG_FILE] [--dry-run] config_file
booktree: error: unrecognized arguments: --file /docker/booktree/logs/booktree_log.csv /docker/booktree/config/config.json
```

"log" also configured in config file.

**Comment by myxdvz** [comment]
log --file are now invalid from commandline, they have been moved to config file that's why you're getting the help result

booktree.py log-config.json --dry-run
