### ISSUE TITLE
Genre/tags support

### ISSUE THREAD

**Issue by swarthy-roll** [myxdvz/booktree#9]
Are there any plans to include support for genres and/or tags?

**Comment by swarthy-roll** [comment]
FYI I forked this project and have been working on adding goodreads support which includes genre/tag support (from goodreads). So while my fork won't include genre support for Audible or MAM, it will for goodreads. I should have a working version in the next few days. Will comment back here when I'm done.

**Comment by swarthy-roll** [comment]
My working version of booktree with added goodreads support is [now available](https://github.com/swarthy-roll/booktree). I don't think it's tested enough or mature enough to merge into this project, but I'm mentioning it here in case anyone else is interested. 

I don't love how I've implemented this, having essentially "bolted" it onto the process in a way that mingles with the MAM metadata. I'd like to eventually split it out as its own separate workflow that can be run on its own or alongside the MAM/Audible processes. I also would like to provide the user with some flexibility in how the scraper behaves. Any feedback you have is welcome!

**Comment by swarthy-roll** [comment]
I found pure GR scraping was hit or miss due to both the awful search functionality of GR and the awful metadata most ebooks have. I've incorporated a hybrid Google/Goodreads approach, but Google is very sensitive to scraping. 

I'm testing some time delays in the script, so we'll see how that goes. The delays majorly affect performance though as you can imagine. So the script will be better suited for maintenance vs updating an existing library (unless you don't mind leaving the script churning for days..). 

I do think the scraping is worth it though. GR's metadata is much better than other sources IME. Will continue to update this thread with my progress, if for nothing else, for posterity.

**Comment by myxdvz** [comment]
> Are there any plans to include support for genres and/or tags?

The latest version now supports genres and tags, but this is still using the audible metadata
